### ISSUE TITLE
Save Custom Options yt-dlp

### ISSUE THREAD

**Issue by candrapersada** [eppic/ytBATCH#4]
how to save Custom Options or custom yt-dlp parameters to config?

**Comment by eppic** [comment]
Under `Preferences` -> `Open yt-dlp Config` you can change the default custom parameters for every download you make.
These Options will always be applied. This is the default yt-dlp config file (--config-location)

The new Custom Parameters for singular downloads, coming with ytBATCH 2.9.2 can not be saved and have to be put in manually every time. Saving custom parameters may come in a future update.

**Comment by candrapersada** [comment]
why `--output '%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s'` or `--output '%(playlist)s/%(title)s.%(ext)s'` not working in `Config`
and why use `youtube-dl.conf` not `yt-dlp.conf`?
![image](https://user-images.githubusercontent.com/36833664/174288175-1dec4366-ae0e-4e96-8ae4-1c863f09dadb.png)

**Comment by eppic** [comment]
`--output` / `-o` is not working because it is already being used everytime ytBATCH downloads with yt-dlp. 2 conflicting output options can not work together. You can change your file destination under `Preferences` -> `Change Output Path` by pasting in your desired path. 

youtube-dl.conf is just the name of the file, it is still used with yt-dlp. In a future update i may change it to something else.

**Comment by candrapersada** [comment]
how to Download YouTube playlist videos in separate directory indexed by video order in a playlist like `"%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"`
and add two conf for yt-dlp and youtube-dl
![image](https://user-images.githubusercontent.com/36833664/174291705-7c78cf55-3cb2-41d2-a143-b24e067511f8.png)

**Comment by eppic** [comment]
There is no option like that right now, but i am working on playlist downloads always being in an extra directory.

Adding 2 seperate config files would be a possibility, but i think it is better to have only 1 config for both.
